author:
  twitter_link: http://twitter.com/ftsanjuan
  github_link: http://github.com/ftsanjuan
  linkedin_link: http://www.linkedin.com/profile/view?id=102478400
  googleplus_link: https://plus.google.com/106039162723592925769
  ftsanjuan_link: http://ftsanjuan.com
  email_link: francis@ftsanjuan.com
  bitbucket_link: http://bitbucket.org/ftsanjuan
  instagram_link: http://instagram.com/ftsanjuan